baseURL = "https://adamtoreilly.info/"
languageCode = "en-us"
title = "Adam Taylor O'Reilly"
enableGitInfo = true

[Params]
mainSections = "work"
goatCounter = "adamoadamo"
tagline = "Adam Taylor O'Reilly is a designer and developer based in Brooklyn, NY."
ga = "G-TF8P2JE3M4"

disableKinds = ["taxonomy", "term", "RSS"]

[markup.goldmark.renderer]
unsafe = true

[permalinks]
work = "/:sections[last]-:filename/"

[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML"]
