baseURL = "http://adamtoreilly.info/"
languageCode = "en-us"
title = "Adam O'Reilly"

[Params]
mainSections = "work"
goatCounter = "adamoadamo"
tagline = "Adam O'Reilly is a designer and developer based in Brooklyn, <nobr>New York</nobr>."
ga = "G-TF8P2JE3M4"

disableKinds = ["taxonomy", "term", "RSS"]

[markup.goldmark.renderer]
unsafe = true

[permalinks]
work = "/:sections[last]-:filename/"
