backend:
  name: github
  repo: adamoadamo/adamo-portfolio
  branch: master
  auth_endpoint: auth
  site_id: ddb84c21-87cf-4153-b84f-e5aee4170d98

site_url: https://adamtoreilly.info
display_url: https://adamtoreilly.info

publish_mode: simple

media_folder: "content/projects/{{dirname}}"
public_folder: "."

collections:
  - name: "bio"
    label: "Bio"
    files:
      - file: "content/_index.md"
        name: "bio"
        label: "Bio Content"
        fields:
          - {label: "Email Link", name: "email_link", widget: "string"}
          - {label: "Instagram Link", name: "instagram_link", widget: "string"}
          - {label: "Github Link", name: "github_link", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown"}

  - name: "footer"
    label: "Footer"
    files:
      - file: "content/footer.md"
        name: "footer"
        label: "Footer Content"
        fields:
          - {label: "Content", name: "body", widget: "markdown"}

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    extension: "md"
    format: "toml-frontmatter"
    identifier_field: "title"
    filter: {field: "section", value: "projects"}
    path: "{{title}}/index"
    summary: "{{title}}"
    sortable_fields: ['title', 'commit_date']
    card: 
      image: "{{resources.[0].src}}"
      text: "{{title}}"
      imageAlt: "{{resources.[0].alt}}"
    view_filters:
      - label: "Has Images"
        field: resources
        pattern: ".+"
    view_groups:
      - label: Year
        field: year
        pattern: '(\d{4})'
    fields:
      - {label: "Project Title", name: "title", widget: "string", required: false}
      - {label: "Section", name: "section", widget: "hidden", default: "projects"}
      - label: "Project Tags"
        name: "project_tags"
        widget: "select"
        multiple: true
        required: false
        options: ["Exhibition", "Identity", "Writing", "Drawing", "Music", "Website", "Coding"]
      - {label: "Role", name: "role", widget: "string", required: false}
      - {label: "Collaborators", name: "collaborators", widget: "string", required: false}
      - {label: "Year", name: "year", widget: "string", required: false}
      - label: "Project Media"
        name: "resources"
        widget: "list"
        required: false
        summary: "{{fields.src}}"
        label_singular: "Media Item"
        fields:
          - label: "Media File"
            name: "src"
            widget: "file"
            required: false
            choose_url: false
            media_folder: "/content/projects/{{dirname}}"
            public_folder: "."
            pattern: ['.*\.(jpg|jpeg|png|gif|webp|mp4)$', "Must be an image (JPG, PNG, GIF, WEBP) or video file (MP4)"]
            filename_template: "{{dirname}}-{{index}}"
            media_library:
              config:
                multiple: true
          - label: "Alt Text"
            name: "alt"
            widget: "string"
            required: true
            hint: "Describe the image/video for accessibility"
      - {label: "Description", name: "body", widget: "markdown", required: false}