name: Alt Text Generator

on: 
  workflow_dispatch

env:
  AZURE_API: ${{ secrets.AZURE_API }}
  VISION_ENDPOINT: ${{ secrets.VISION_ENDPOINT }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install azure-ai-vision
          pip install toml requests 

      - name: Run Python Script
        run: python ./assets/scripts/alt.py
