name: Alt Text Generator

on: 
  workflow_dispatch

env:
  AZURE_API: ${{ secrets.AZURE_API }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install requests pyyaml

      - name: Run Python Script
        run: python ././assets/scripts/alt.py
